### ISSUE TITLE
Raise a PR for integrating into Apache NetBeans GitHub

### ISSUE THREAD

**Issue by SamSharaf** [hlavki/netbeans-svuid-generator#3]
Hi @hlavki 
Kindly raise a PR for integrating into Apache NetBeans GitHub https://github.com/apache/netbeans
This issue is encouraged by @geertjanw as in the tweet https://twitter.com/GeertjanW/status/1234572192286986245?s=20

**Comment by hlavki** [comment]
thanks @SamSharaf, part of this plugin is already included in netbean distribution:
https://github.com/apache/netbeans/blob/master/java/java.hints/src/org/netbeans/modules/java/hints/SerialVersionUID.java

I am not sure if integration to netbeans is good idea, since svuid generator is not fully compliant with specification. It does not include static code part. I think better option is to release plugin to new plugin portal.

**Comment by SamSharaf** [comment]
@hlavki, I totally agree.
I hope you may find time to release it to the the new plugin portal.
I believe @junichi11 or @emilianbold know more about the new plugin portal than myself

**Comment by SamSharaf** [comment]
@hlavki, feel free to close this issue according to your convenience.
Be save and healthy!

**Comment by hlavki** [comment]
Released plugin to [maven central](https://repo1.maven.org/maven2/eu/hlavki/netbeans/netbeans-svuid-generator/3.0/) and waiting for approval in plugin portal
